### ISSUE TITLE
Fix authorization

### ISSUE THREAD

**Issue by avirix** [Vfed/APITest#1]
https://github.com/Vfed/APITest/blob/3ebfc573042543662d441fe3601d61d149fb9c38/Startup.cs#L71
Order of Use...() is important!

app.UseAuthentication();
app.UseAuthorization();

![image](https://user-images.githubusercontent.com/29061919/140589505-753ac2ff-0adf-4f39-9108-001a6cf29c31.png)

**Comment by Vfed** [comment]
Fixed , order changed
